"""
SQLAlchemy Models for CampusGPT

Migration note: All new columns are nullable so that `Base.metadata.create_all`
(run at startup) safely adds them to an existing schema via SQLite's
`CREATE TABLE IF NOT EXISTS` semantics.
TODO (post-MVP): Introduce Alembic for proper versioned migrations before any
production deployment that requires zero-downtime schema changes.
"""
import json
from datetime import datetime, timezone
from sqlalchemy import (
    String, Integer, Float, Text, Boolean,
    DateTime, ForeignKey, JSON
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ─── Conversation ─────────────────────────────────────────────────────────────

class Conversation(Base):
    __tablename__ = "conversations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    title: Mapped[str] = mapped_column(String(255), default="New Conversation")

    # Feature #5: User ownership — optional string (browser UUID for now).
    # Designed to be replaced by JWT `sub` later without schema changes.
    # Conversations where user_id is NULL are treated as legacy/public.
    user_id: Mapped[str | None] = mapped_column(String(128), nullable=True, index=True)

    # Feature #2: Running summary generated by Gemini when message count ≥ threshold.
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    summary_updated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)

    messages: Mapped[list["Message"]] = relationship(
        "Message", back_populates="conversation", cascade="all, delete-orphan"
    )
    memories: Mapped[list["ConversationMemory"]] = relationship(
        "ConversationMemory", back_populates="conversation", cascade="all, delete-orphan"
    )


# ─── Message ──────────────────────────────────────────────────────────────────

class Message(Base):
    __tablename__ = "messages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    conversation_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("conversations.id", ondelete="CASCADE"), index=True
    )
    role: Mapped[str] = mapped_column(String(20))          # "user" | "assistant"
    content: Mapped[str] = mapped_column(Text)
    # JSON-encoded list of source citations
    sources_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Feature #3: Full retrieved & reranked chunk data for debugging / analytics.
    retrieved_chunks_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)

    conversation: Mapped["Conversation"] = relationship("Conversation", back_populates="messages")
    feedback: Mapped[list["Feedback"]] = relationship(
        "Feedback", back_populates="message", cascade="all, delete-orphan"
    )

    @property
    def sources(self) -> list[dict]:
        if self.sources_json:
            return json.loads(self.sources_json)
        return []

    @property
    def retrieved_chunks(self) -> list[dict]:
        if self.retrieved_chunks_json:
            return json.loads(self.retrieved_chunks_json)
        return []


# ─── Feedback ─────────────────────────────────────────────────────────────────

class Feedback(Base):
    __tablename__ = "feedback"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    message_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("messages.id", ondelete="CASCADE"), index=True
    )
    rating: Mapped[str] = mapped_column(String(10))  # "helpful" | "not_helpful"
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)

    message: Mapped["Message"] = relationship("Message", back_populates="feedback")


# ─── Document ─────────────────────────────────────────────────────────────────

class Document(Base):
    __tablename__ = "documents"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    filename: Mapped[str] = mapped_column(String(255))
    original_filename: Mapped[str] = mapped_column(String(255))
    category: Mapped[str] = mapped_column(String(100), default="general")
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    chunk_count: Mapped[int] = mapped_column(Integer, default=0)
    # "pending" | "indexing" | "indexed" | "error"
    status: Mapped[str] = mapped_column(String(20), default="pending")
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    file_size_bytes: Mapped[int] = mapped_column(Integer, default=0)
    uploaded_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    indexed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)


# ─── Analytics Event ──────────────────────────────────────────────────────────

class AnalyticsEvent(Base):
    __tablename__ = "analytics_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    event_type: Mapped[str] = mapped_column(String(50))  # "query" | "upload" | "feedback"
    query: Mapped[str | None] = mapped_column(Text, nullable=True)
    conversation_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    response_time_ms: Mapped[float | None] = mapped_column(Float, nullable=True)
    retrieved_chunks: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)


# ─── Response Cache ───────────────────────────────────────────────────────────
# Feature #4: Persistent cache backing store.
# In-memory LRU (cache_service.py) is the hot path; this table survives restarts.

class ResponseCache(Base):
    __tablename__ = "response_cache"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    # Canonical query text (for logging/debugging)
    query_text: Mapped[str] = mapped_column(Text)
    # BGE embedding stored as JSON float array
    query_embedding_json: Mapped[str] = mapped_column(Text)
    # The knowledge version at the time this entry was cached.
    # If current knowledge_version != this value the entry is stale and ignored.
    knowledge_version: Mapped[int] = mapped_column(Integer, default=0, index=True)
    # Cached LLM answer
    answer: Mapped[str] = mapped_column(Text)
    # JSON-encoded list of SourceCitation dicts
    sources_json: Mapped[str] = mapped_column(Text, default="[]")
    hit_count: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    expires_at: Mapped[datetime] = mapped_column(DateTime, index=True)


# ─── Knowledge Version ────────────────────────────────────────────────────────
# Feature #4: Single-row counter incremented whenever the knowledge base changes
# (document upload, update, delete, re-index). Cache entries with a stale
# knowledge_version are ignored, achieving instant invalidation without a scan.

class KnowledgeVersion(Base):
    __tablename__ = "knowledge_version"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)  # always id=1
    version: Mapped[int] = mapped_column(Integer, default=0)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)


# ─── Conversation Memory ──────────────────────────────────────────────────────
# Feature #7: Per-conversation memory entries for long-term retrieval.
# The storage interface is abstracted in memory_service.py — swap the backend
# to Qdrant by replacing only that service without touching the chat pipeline.

class ConversationMemory(Base):
    __tablename__ = "conversation_memories"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    conversation_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("conversations.id", ondelete="CASCADE"), index=True
    )
    # Human-readable summary of the remembered turn(s)
    content_summary: Mapped[str] = mapped_column(Text)
    # BGE embedding of content_summary stored as JSON float array
    embedding_json: Mapped[str] = mapped_column(Text)
    # Which message IDs this memory covers (e.g., "42-45")
    turn_range: Mapped[str | None] = mapped_column(String(50), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)

    conversation: Mapped["Conversation"] = relationship(
        "Conversation", back_populates="memories"
    )
